set define off
set serveroutput on
set verify off
whenever sqlerror exit sql.sqlcode rollback
whenever oserror exit failure rollback

prompt Installing cooperative Oracle DEV object locks...

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'DEV_OBJECT_LOCK';

    if l_count = 0 then
        execute immediate q'[
            create table dev_object_lock
            (
                ad_dev_object_lock number generated by default on null as identity not null,
                object_owner varchar2(128) default user not null,
                object_type varchar2(30) not null,
                object_name varchar2(128) not null,
                lock_status varchar2(20) default 'ACTIVE' not null,
                locked_by varchar2(255) not null,
                branch_name varchar2(255),
                task_ref varchar2(500),
                lock_context varchar2(4000),
                repo_base_ref varchar2(255),
                repo_head_ref varchar2(255),
                repo_start_sha varchar2(64),
                repo_end_sha varchar2(64),
                locked_at timestamp with time zone default systimestamp not null,
                last_heartbeat_at timestamp with time zone default systimestamp not null,
                lock_expires_at timestamp with time zone not null,
                released_at timestamp with time zone,
                released_by varchar2(255),
                release_reason varchar2(4000),
                constraint dev_object_lock_pk primary key (ad_dev_object_lock),
                constraint dev_object_lock_status_ck
                    check (lock_status in ('ACTIVE', 'RELEASED', 'EXPIRED')),
                constraint dev_object_lock_type_ck
                    check (object_type in (
                        'PACKAGE',
                        'VIEW',
                        'TRIGGER',
                        'PROCEDURE',
                        'FUNCTION',
                        'TYPE',
                        'SYNONYM'
                    ))
            )
        ]';
    end if;
end;
/

declare
    procedure add_column_if_missing (
        p_column_name in varchar2,
        p_definition  in varchar2
    )
    is
        l_count number;
    begin
        select count(*)
          into l_count
          from user_tab_columns
         where table_name = 'DEV_OBJECT_LOCK'
           and column_name = upper(p_column_name);

        if l_count = 0 then
            execute immediate
                'alter table dev_object_lock add (' ||
                dbms_assert.simple_sql_name(p_column_name) || ' ' ||
                p_definition || ')';
        end if;
    end add_column_if_missing;
begin
    add_column_if_missing('REPO_BASE_REF',  'VARCHAR2(255)');
    add_column_if_missing('REPO_HEAD_REF',  'VARCHAR2(255)');
    add_column_if_missing('REPO_START_SHA', 'VARCHAR2(64)');
    add_column_if_missing('REPO_END_SHA',   'VARCHAR2(64)');
end;
/

declare
    procedure add_constraint_if_missing (
        p_constraint_name in varchar2,
        p_definition      in varchar2
    )
    is
        l_count number;
    begin
        select count(*)
          into l_count
          from user_constraints
         where table_name = 'DEV_OBJECT_LOCK'
           and constraint_name = upper(p_constraint_name);

        if l_count = 0 then
            execute immediate
                'alter table dev_object_lock add constraint ' ||
                dbms_assert.simple_sql_name(p_constraint_name) || ' ' ||
                p_definition;
        end if;
    end add_constraint_if_missing;
begin
    add_constraint_if_missing(
        'DEV_OBJECT_LOCK_PK',
        'primary key (ad_dev_object_lock)'
    );
    add_constraint_if_missing(
        'DEV_OBJECT_LOCK_STATUS_CK',
        q'[check (lock_status in ('ACTIVE', 'RELEASED', 'EXPIRED'))]'
    );
    add_constraint_if_missing(
        'DEV_OBJECT_LOCK_TYPE_CK',
        q'[check (object_type in (
            'PACKAGE',
            'VIEW',
            'TRIGGER',
            'PROCEDURE',
            'FUNCTION',
            'TYPE',
            'SYNONYM'
        ))]'
    );
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_indexes
     where index_name = 'DEV_OBJECT_LOCK_UI1';

    if l_count = 0 then
        execute immediate q'[
            create unique index dev_object_lock_ui1 on dev_object_lock
            (
                case when lock_status = 'ACTIVE' then object_owner end,
                case when lock_status = 'ACTIVE' then object_type end,
                case when lock_status = 'ACTIVE' then object_name end
            )
        ]';
    end if;

    select count(*)
      into l_count
      from user_indexes
     where index_name = 'DEV_OBJECT_LOCK_I1';

    if l_count = 0 then
        execute immediate q'[
            create index dev_object_lock_i1
                on dev_object_lock (lock_status, lock_expires_at)
        ]';
    end if;
end;
/

create or replace editionable view vw_dev_object_lock_ativo as
select ad_dev_object_lock,
       object_owner,
       object_type,
       object_name,
       locked_by,
       branch_name,
       task_ref,
       lock_context,
       repo_base_ref,
       repo_head_ref,
       repo_start_sha,
       repo_end_sha,
       locked_at,
       last_heartbeat_at,
       lock_expires_at
  from dev_object_lock
 where lock_status = 'ACTIVE'
   and lock_expires_at >= systimestamp;

create or replace editionable view vw_dev_object_lock_recente as
select ad_dev_object_lock,
       object_owner,
       object_type,
       object_name,
       lock_status,
       locked_by,
       branch_name,
       task_ref,
       lock_context,
       repo_base_ref,
       repo_head_ref,
       repo_start_sha,
       repo_end_sha,
       locked_at,
       last_heartbeat_at,
       lock_expires_at,
       released_at,
       released_by,
       release_reason
  from dev_object_lock
 where nvl(released_at, last_heartbeat_at) >=
       systimestamp - interval '48' hour;

@@packages/pk_dev_object_lock.pks
show errors package PK_DEV_OBJECT_LOCK

@@packages/pk_dev_object_lock.pkb
show errors package body PK_DEV_OBJECT_LOCK

begin
    pk_dev_object_lock.proc_expirar_locks;
end;
/

declare
    l_missing number;
    l_invalid number;
    l_unusable_indexes number;
    l_errors  number;
    l_columns number;
    l_constraints number;
    l_version varchar2(20);
begin
    select count(*)
      into l_missing
      from (
            select 'DEV_OBJECT_LOCK' object_name, 'TABLE' object_type from dual
            union all select 'DEV_OBJECT_LOCK_UI1', 'INDEX' from dual
            union all select 'DEV_OBJECT_LOCK_I1', 'INDEX' from dual
            union all select 'VW_DEV_OBJECT_LOCK_ATIVO', 'VIEW' from dual
            union all select 'VW_DEV_OBJECT_LOCK_RECENTE', 'VIEW' from dual
            union all select 'PK_DEV_OBJECT_LOCK', 'PACKAGE' from dual
            union all select 'PK_DEV_OBJECT_LOCK', 'PACKAGE BODY' from dual
           ) expected
     where not exists (
               select 1
                 from user_objects actual
                where actual.object_name = expected.object_name
                  and actual.object_type = expected.object_type
           );

    select count(*)
      into l_invalid
      from user_objects
     where object_name in (
               'DEV_OBJECT_LOCK',
               'VW_DEV_OBJECT_LOCK_ATIVO',
               'VW_DEV_OBJECT_LOCK_RECENTE',
               'PK_DEV_OBJECT_LOCK'
           )
       and status <> 'VALID';

    select count(*)
      into l_unusable_indexes
      from user_indexes
     where index_name in ('DEV_OBJECT_LOCK_UI1', 'DEV_OBJECT_LOCK_I1')
       and status <> 'VALID';

    select count(*)
      into l_columns
      from user_tab_columns
     where table_name = 'DEV_OBJECT_LOCK'
       and column_name in (
               'AD_DEV_OBJECT_LOCK',
               'OBJECT_OWNER',
               'OBJECT_TYPE',
               'OBJECT_NAME',
               'LOCK_STATUS',
               'LOCKED_BY',
               'BRANCH_NAME',
               'TASK_REF',
               'LOCK_CONTEXT',
               'REPO_BASE_REF',
               'REPO_HEAD_REF',
               'REPO_START_SHA',
               'REPO_END_SHA',
               'LOCKED_AT',
               'LAST_HEARTBEAT_AT',
               'LOCK_EXPIRES_AT',
               'RELEASED_AT',
               'RELEASED_BY',
               'RELEASE_REASON'
           );

    select count(*)
      into l_constraints
      from user_constraints
     where table_name = 'DEV_OBJECT_LOCK'
       and constraint_name in (
               'DEV_OBJECT_LOCK_PK',
               'DEV_OBJECT_LOCK_STATUS_CK',
               'DEV_OBJECT_LOCK_TYPE_CK'
           )
       and status = 'ENABLED';

    select count(*)
      into l_errors
      from user_errors
     where name = 'PK_DEV_OBJECT_LOCK';

    l_version := pk_dev_object_lock.func_runtime_version;

    if l_missing > 0
       or l_invalid > 0
       or l_unusable_indexes > 0
       or l_errors > 0
       or l_columns <> 19
       or l_constraints <> 3
    then
        raise_application_error(
            -20089,
            'Object-lock runtime validation failed: missing=' ||
            l_missing || ', invalid=' || l_invalid ||
            ', unusable_indexes=' || l_unusable_indexes ||
            ', errors=' || l_errors ||
            ', columns=' || l_columns || '/19' ||
            ', constraints=' || l_constraints || '/3'
        );
    end if;

    if l_version <> '1.0.0' then
        raise_application_error(
            -20091,
            'Unexpected object-lock runtime version: ' || l_version
        );
    end if;

    dbms_output.put_line(
        'ORACLE_APEX_OBJECT_LOCK_STATUS=INSTALLED;VERSION=' || l_version
    );
end;
/

prompt Cooperative Oracle DEV object locks installed and validated.
exit success
