set define off
set serveroutput on
set verify off
whenever sqlerror exit sql.sqlcode rollback
whenever oserror exit failure rollback

select user as database_user,
       sys_context('USERENV', 'SERVICE_NAME') as service_name
  from dual;

prompt Installing cooperative Oracle DEV object locks...

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_tables
     where table_name = 'DEV_OBJECT_LOCK';

    if l_count = 0 then
        execute immediate q'[
            create table dev_object_lock
            (
                ad_dev_object_lock number generated by default on null as identity not null,
                object_owner varchar2(128 char) default user not null,
                object_type varchar2(30 char) not null,
                object_name varchar2(128 char) not null,
                lock_status varchar2(20 char) default 'ACTIVE' not null,
                locked_by varchar2(255 char) not null,
                branch_name varchar2(255 char),
                task_ref varchar2(500 char),
                lock_context varchar2(4000 byte),
                repo_base_ref varchar2(255 char),
                repo_head_ref varchar2(255 char),
                repo_start_sha varchar2(64 char),
                repo_end_sha varchar2(64 char),
                locked_at timestamp with time zone default systimestamp not null,
                last_heartbeat_at timestamp with time zone default systimestamp not null,
                lock_expires_at timestamp with time zone not null,
                released_at timestamp with time zone,
                released_by varchar2(255 char),
                release_reason varchar2(4000 byte),
                constraint dev_object_lock_pk primary key (ad_dev_object_lock),
                constraint dev_object_lock_status_ck
                    check (lock_status in ('ACTIVE', 'RELEASED', 'EXPIRED')),
                constraint dev_object_lock_type_ck
                    check (object_type in (
                        'PACKAGE',
                        'VIEW',
                        'TRIGGER',
                        'PROCEDURE',
                        'FUNCTION',
                        'TYPE',
                        'SYNONYM'
                    ))
            )
        ]';
    end if;
end;
/

declare
    procedure add_column_if_missing (
        p_column_name in varchar2,
        p_definition  in varchar2
    )
    is
        l_count number;
    begin
        select count(*)
          into l_count
          from user_tab_columns
         where table_name = 'DEV_OBJECT_LOCK'
           and column_name = upper(p_column_name);

        if l_count = 0 then
            execute immediate
                'alter table dev_object_lock add (' ||
                dbms_assert.simple_sql_name(p_column_name) || ' ' ||
                p_definition || ')';
        end if;
    end add_column_if_missing;
begin
    add_column_if_missing('REPO_BASE_REF',  'VARCHAR2(255 CHAR)');
    add_column_if_missing('REPO_HEAD_REF',  'VARCHAR2(255 CHAR)');
    add_column_if_missing('REPO_START_SHA', 'VARCHAR2(64 CHAR)');
    add_column_if_missing('REPO_END_SHA',   'VARCHAR2(64 CHAR)');
end;
/

alter table dev_object_lock modify (
    object_owner varchar2(128 char),
    object_type varchar2(30 char),
    object_name varchar2(128 char),
    lock_status varchar2(20 char),
    locked_by varchar2(255 char),
    branch_name varchar2(255 char),
    task_ref varchar2(500 char),
    lock_context varchar2(4000 byte),
    repo_base_ref varchar2(255 char),
    repo_head_ref varchar2(255 char),
    repo_start_sha varchar2(64 char),
    repo_end_sha varchar2(64 char),
    released_by varchar2(255 char),
    release_reason varchar2(4000 byte)
);

declare
    procedure add_constraint_if_missing (
        p_constraint_name in varchar2,
        p_definition      in varchar2
    )
    is
        l_count number;
    begin
        select count(*)
          into l_count
          from user_constraints
         where table_name = 'DEV_OBJECT_LOCK'
           and constraint_name = upper(p_constraint_name);

        if l_count = 0 then
            execute immediate
                'alter table dev_object_lock add constraint ' ||
                dbms_assert.simple_sql_name(p_constraint_name) || ' ' ||
                p_definition;
        end if;
    end add_constraint_if_missing;
begin
    add_constraint_if_missing(
        'DEV_OBJECT_LOCK_PK',
        'primary key (ad_dev_object_lock)'
    );
    add_constraint_if_missing(
        'DEV_OBJECT_LOCK_STATUS_CK',
        q'[check (lock_status in ('ACTIVE', 'RELEASED', 'EXPIRED'))]'
    );
    add_constraint_if_missing(
        'DEV_OBJECT_LOCK_TYPE_CK',
        q'[check (object_type in (
            'PACKAGE',
            'VIEW',
            'TRIGGER',
            'PROCEDURE',
            'FUNCTION',
            'TYPE',
            'SYNONYM'
        ))]'
    );
end;
/

declare
    l_count number;
begin
    select count(*)
      into l_count
      from user_indexes
     where index_name = 'DEV_OBJECT_LOCK_UI1';

    if l_count = 0 then
        execute immediate q'[
            create unique index dev_object_lock_ui1 on dev_object_lock
            (
                case when lock_status = 'ACTIVE' then object_owner end,
                case when lock_status = 'ACTIVE' then object_type end,
                case when lock_status = 'ACTIVE' then object_name end
            )
        ]';
    end if;

    select count(*)
      into l_count
      from user_indexes
     where index_name = 'DEV_OBJECT_LOCK_I1';

    if l_count = 0 then
        execute immediate q'[
            create index dev_object_lock_i1
                on dev_object_lock (lock_status, lock_expires_at)
        ]';
    end if;
end;
/

create or replace editionable view vw_dev_object_lock_ativo as
select ad_dev_object_lock,
       object_owner,
       object_type,
       object_name,
       locked_by,
       branch_name,
       task_ref,
       lock_context,
       repo_base_ref,
       repo_head_ref,
       repo_start_sha,
       repo_end_sha,
       locked_at,
       last_heartbeat_at,
       lock_expires_at
  from dev_object_lock
 where lock_status = 'ACTIVE'
   and lock_expires_at >= systimestamp;

create or replace editionable view vw_dev_object_lock_recente as
select ad_dev_object_lock,
       object_owner,
       object_type,
       object_name,
       lock_status,
       locked_by,
       branch_name,
       task_ref,
       lock_context,
       repo_base_ref,
       repo_head_ref,
       repo_start_sha,
       repo_end_sha,
       locked_at,
       last_heartbeat_at,
       lock_expires_at,
       released_at,
       released_by,
       release_reason
  from dev_object_lock
 where nvl(released_at, last_heartbeat_at) >=
       systimestamp - interval '48' hour;

@@packages/pk_dev_object_lock.pks
show errors package PK_DEV_OBJECT_LOCK

@@packages/pk_dev_object_lock.pkb
show errors package body PK_DEV_OBJECT_LOCK

begin
    pk_dev_object_lock.proc_expirar_locks;
end;
/
prompt Cooperative Oracle DEV object locks compiled. Running strict validation...
@@validate-installation.sql
exit success
